# apps/web-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/toddlers/argocd-example-apps.git
        revision: HEAD
        directories:
          - path: kustomize-web/overlays/*
  template:
    metadata:
      name: "web-{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/toddlers/argocd-example-apps.git
        targetRevision: HEAD
        path: "kustomize-web/overlays/{{.path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "web-{{.path.basename}}"
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]
