apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-dev
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  project: default
  source:
    repoURL: https://github.com/toddlers/argocd-example-apps
    targetRevision: HEAD
    path: kustomize-web/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: web-dev
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
